### ISSUE TITLE
Introduce MetaPack Desktop Client

### ISSUE THREAD

**Issue by SubPointSupport** [SubPointSolutions/MetaPack#6]
MetaPack Desktop client needs to be migrated under GitHub repository.
* [x] move initial source code to GitHub
* [x] enhance CI build to create both zip/chocolatey packages

**Comment by norvegec** [comment]
I'm intrested in it. Milestones?

**Comment by SubPointSupport** [comment]
We are releasing metapack cli this / following week, and close to the end of November will get GUI done.

**Comment by SubPointSupport** [comment]
Finally, getting releases this week.
